{
    "Service": "/Customer/Services/SampleServiceV4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "ProductCategories",
            "Query": "ProductCategories"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "ProductTexts",
            "Query": "ProductTexts"
        },
        {
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        },
        {
            "Name": "SalesOrderHeaders",
            "Query": "SalesOrderHeaders"
        },
        {
            "Name": "SalesOrderItems",
            "Query": "SalesOrderItems"
        },
        {
            "Name": "Stock",
            "Query": "Stock"
        },
        {
            "Name": "Suppliers",
            "Query": "Suppliers"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnSuccess": "/Customer/Actions/Service/InitializeOfflineSuccessMessage.action",
    "OnFailure": "/Customer/Actions/Service/InitializeOfflineFailureMessage.action"
}