{
    "Service": "/Customer/Services/SampleServiceV4.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/Customer/Actions/Service/DownloadStartedMessage.action",
    "OnFailure": "/Customer/Actions/Service/SyncFailureMessage.action"
}